### PR TITLE
Added Support For Inf Buttons Auto Config Updater Color Tags And Also Custom Forms With a example usage of a captcha system made by me!

### PR DESCRIPTION
**Pull request by Jviguy**
Added Support For Inf Buttons Auto Config Updater Color Tags And Also Custom Forms With a example usage of a captcha system made by me!

### CODE REVIEW

**Comment by Kygekraqmak** [comment]
Before I review this plugin, I need to know some things. First, what's CAPTCHA for? Is it useful? Second, does the plugin contains bugs/lints. Please test the plugin first.

**Comment by Jviguy** [comment]
ive tested most of it everything works and the captcha can be taken out its basically to stop from bots from joining your server its an example usage it can also be used for passwords and account systems if u find a way to.

**Comment by Kygekraqmak** [comment]
So this plugin will need SimpleAuth to work?

**Comment by Jviguy** [comment]
no

**Comment by Kygekraqmak** [comment]
Please check the lint [here](https://poggit.pmmp.io/babs/149fd)

**Comment by Jviguy** [comment]
`$path = $this->getConfig()->getPath();` does exist as seen in the documentary from here https://jenkins.pmmp.io/job/PocketMine-MP-doc/doxygen/d6/d2c/classpocketmine_1_1utils_1_1_config.html#a601ce3859a6a56b18aaba1ea7ead57c5

**Comment by NhanAZ** [comment]
This pull request is outdated... Should it be closed? @MintoD

**Comment by KygekDev** [comment]
Agree, close it.

**Comment by NhanAZ** [comment]
@Jviguy Thanks for your pull request. I will be closing this pull request as it is no longer active and outdated.

**Pull request closed without merging**
